apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: ManagedCluster
metadata:
  name: alpha
spec:
  subscriptionId: 8643025a-c059-4a48-85d0-d76f51d63a74
  resourceGroup: ace-test
  location: westus2
  name: ace-alpha
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnafEQ91LfDdcpuPP52nxVkwgdDXhbZHFUsSLdfPYWsbgv+1+nThMBimYWIUmnoQnlFaz9lEbvj7gh+oZf/DEaLHNdFgI0JTAroI4hgHShGL/dg+javFp2b2TqpAmDditsA1xxsSPNsWCqSkcD1vOh6/ucX0QT50yI+lf/CuB+5HadC47b5fB0yFeipLe8HhkAdipuoSEuY5wpt37nsSDIeLVHUPRbSSPt14h1Ot2ni3vQGsyfZgGvDa/GT7tq3FZbQe7n7EIhqA8vdtey1+iztBXJIjqkO0nUwJM/aTvhbgwg1sKWH5xmb61vKQpmTP2imgcn5YMMxLr11hED13v7 ace@ace-x1
  version: 1.16.4
  credentialsRef:
    name: azure-creds
    namespace: azsvc-system
  nodePools:
  - name: small
    sku: Standard_B2ms
    replicas: 3
    osDiskSizeGb: 250
  - name: main 
    sku: Standard_D4_v3
    replicas: 4
    osDiskSizeGb: 500
  kustomizations:
  # - https://github.com/alexeldeib/cd-example
  - github.com/alexeldeib/azsvc/workloads/fluentbit?ref=ace/svc-dev
  - github.com/alexeldeib/azsvc/workloads/prom-to-log?ref=ace/svc-dev
  - github.com/alexeldeib/azsvc/workloads/prometheus?ref=ace/svc-dev
  - github.com/alexeldeib/azsvc/workloads/certmanager?ref=ace/svc-dev
  - github.com/juan-lee/stressed/config/default?ref=master
  manifests:
  # - https://gist.githubusercontent.com/alexeldeib/ba6d782d12d3606a4054fd5af56e621d/raw/8d2eee159674ab2eb4160415e82f5d26dbda1fd1/stress.yaml
  # - https://gist.githubusercontent.com/alexeldeib/755a276aba83311133e964f90dae796c/raw/ad719bc5947ad1dc14bea7e8e4e878c04f54dbc9/apply.yaml
  objectRefs:
  - kind: Secret
    apiVersion: v1
    name: gcscert
    namespace: default