apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  labels:
    k8s-app: fluent-bit
data:
  mdsd: |
    # Options for mdsd
    # Check 'mdsd -h' for details.
   
    MDSD_ROLE_PREFIX=/var/run/mdsd/default
    #MDSD_OPTIONS="-d -A -r ${MDSD_ROLE_PREFIX}"

    # If this is changed, also change /etc/logrotate.d/mdsd
    MDSD_LOG=/var/log
    
    # This is where rsyslog and eventhub messages are spooled.
    MDSD_SPOOL_DIRECTORY=/var/opt/microsoft/linuxmonagent
    
    MDSD_OPTIONS="-a -f 5001 -c /etc/mdsd.d/mdsd.xml -r $MDSD_ROLE_PREFIX -S $MDSD_SPOOL_DIRECTORY/eh -e $MDSD_LOG/mdsd.err -w $MDSD_LOG/mdsd.warn -o $MDSD_LOG/mdsd.info"
    
    export SSL_CERT_DIR=/etc/ssl/certs
    #SSL_CERT_FILE
    
    # For instructions on configuring mdsd for GCS, see:
    # https://jarvis-west.dc.ad.msft.net/?page=documents&section=9c95f4eb-8689-4c9f-81bf-82d688e860fd&id=69cfaf8a-6417-41b7-a7b4-8d686c4173fe
    # In order to enable GCS, uncomment and set all 5 GCS environment variables below
   
    # REQUIRED
    # Geneva environment. Examples: Test, FirstPartyProd, DiagnosticsProd
    # For the full list of environments, see:
    # https://jarvis-west.dc.ad.msft.net/?page=documents&section=1363da01-b6ed-43d4-970e-f89b011d591f&id=d18a0cdb-eb0e-485b-b1bb-cbb6069d352b
    #
    export MONITORING_GCS_ENVIRONMENT=Test
    
    # REQUIRED
    # Geneva Account name
    #
    export MONITORING_GCS_ACCOUNT=aksdataplane
    
    # REQUIRED
    # The region GCS should use when it determines which storage account credentials it should return to MA. e.g. "westus", "eastus".
    # Generally, it's best to obtain this value on the VM hosting the agent by querying the Azure Instance Metadata Service (IMDS) for the "location" value (see above code snippet).
    #
    export MONITORING_GCS_REGION=southcentralus
    # or, pulling data from IMDS
    #imdsURL="http://169.254.169.254/metadata/instance/compute/location?api-version=2017-04-02\&format=text"
    #export MONITORING_GCS_REGION="$(curl -H Metadata:True --silent $imdsURL)"
    
    # REQUIRED
    # Full path to public certificate file used to authenticate mdsd with GCS service.
    #
    export MONITORING_GCS_CERT_CERTFILE=/etc/mdsd.d/certs/gcscert.pem
    
    # REQUIRED
    # Full path to the private key file used to authenticate mdsd with GCS service.
    #
    export MONITORING_GCS_CERT_KEYFILE=/etc/mdsd.d/certs/gcskey.pem
    
    # Below are to enable GCS config download. Update for your namespace and config version.
    export MONITORING_GCS_NAMESPACE=aksdataplane
    export MONITORING_CONFIG_VERSION=1.0
    export MONITORING_USE_GENEVA_CONFIG_SERVICE=true

    export MONITORING_TENANT=southcentralus
    export MONITORING_ROLE=aksdataplane
    export MONITORING_ROLE_INSTANCE=${ROLE_INSTANCE}
  mdsd.xml: |
    <MonitoringManagement eventVersion="1" version="1.0" timestamp="2018-05-07T00:00:00Z" namespace="aksdataplane">
      <Accounts>
        <Account moniker="aksdataplanediag" isDefault="true" />
        <Account moniker="aksdataplanesecurity" alias="AzSecurityStore" />
        <Account moniker="aksdataplaneaudit" alias="AuditStore" />
      </Accounts>
      <!-- Linux mdsd usage documentation: https://jarvis.dc.ad.msft.net/?page=documents&section=1363da01-b6ed-43d4-970e-f89b011d591f&id=89b7a7f4-8cf1-4a76-b541-478d37fc760f  -->
      <Management eventVolume="Medium" defaultRetentionInDays="29">
        <!--
          The identity TenantRole means MONITORING_TENANT, MONITORING_ROLE, and MONITORING_ROLE_INSTANCE will
          uniquely identify any of your instances
        -->
        <Identity type="TenantRole" />
        <!--
          The diskQuotaInMB is a required parameter.  For 10,000 MB there should be 15,000 MB available on the disk  The CPU, memory and network can also be limited in the
          AgentResourceUsage element's attributes.
        -->
        <AgentResourceUsage diskQuotaInMB="50000" cpuPercentUsage="50" />
        <AgentMetrics mdmMonitoringAccount="aks-data-plane" />
      </Management>
      <Schemas>
        <Schema name="syslog">
          <Column name="Facility" mdstype="mt:wstr" type="str" />
          <Column name="Severity" mdstype="mt:int32" type="str" />
          <Column name="EventTime" mdstype="mt:utc" type="str-rfc3339" />
          <Column name="SendingHost" mdstype="mt:wstr" type="str" />
          <Column name="Msg" mdstype="mt:wstr" type="str" />
          <Column name="ProcessId" mdstype="mt:int32" type="str" />
        </Schema>
        <Schema name="azsecv1">
          <Column name="Facility" mdstype="mt:wstr" type="str" />
          <Column name="Severity" mdstype="mt:int32" type="str" />
          <Column name="EventTime" mdstype="mt:utc" type="str-rfc3339" />
          <Column name="SendingHost" mdstype="mt:wstr" type="str" />
          <Column name="Msg" mdstype="mt:wstr" type="str" />
        </Schema>
        <Schema name="azsecv2">
          <Column name="AzSecID" mdstype="mt:wstr" type="str" />
          <Column name="ScanName" mdstype="mt:wstr" type="str" />
          <Column name="EventTime" mdstype="mt:utc" type="str-rfc3339" />
          <Column name="Data" mdstype="mt:wstr" type="str" />
          <Column name="PartCount" mdstype="mt:int32" type="str" />
          <Column name="PartIndex" mdstype="mt:int32" type="str" />
        </Schema>
      </Schemas>
      <Sources>
        <Source name="kern" schema="syslog" />
        <Source name="auth" schema="syslog" />
        <Source name="authpriv" schema="syslog" />
        <Source name="cron" schema="syslog" />
        <Source name="user" schema="syslog" />
        <Source name="daemon" schema="syslog" />
        <Source name="syslog" dynamic_schema="true"/>
        <Source name="heartbeat" schema="azsecv1" />
        <Source name="baseline" schema="azsecv1" />
        <Source name="software" schema="azsecv1" />
        <Source name="clamav" schema="azsecv1" />
        <Source name="scan_event" schema="azsecv2" />
        <Source name="alert" schema="azsecv2" />
        <Source name="audit" dynamic_schema="true" />
        <Source name="kubelog" dynamic_schema="true" />
      </Sources>
      <!-- Linux events documentation: https://jarvis.dc.ad.msft.net/?page=documents&section=9c95f4eb-8689-4c9f-81bf-82d688e860fd&id=762a440d-3a1e-4ff3-86d6-03c491c163b2   -->
      <!--
          Events can contain one or more Event elements.  The Event elements each describe a different kind of collector.
          Events must be defined in the order of the mds2.xsd.
      -->
      <Events>
        <MdsdEvents>
          <MdsdEventSource source="kern">
            <RouteEvent eventName="LinuxAsmSecurity" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="auth">
            <RouteEvent eventName="LinuxAsmSecurity" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="authpriv">
            <RouteEvent eventName="LinuxAsmSecurity" priority="High" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="cron">
            <RouteEvent eventName="LinuxAsmSyslog" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="user">
            <RouteEvent eventName="LinuxAsmSyslog" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="daemon">
            <RouteEvent eventName="LinuxAsmSyslog" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="syslog">
            <RouteEvent eventName="syslog" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="heartbeat">
            <RouteEvent eventName="LinuxAsmHeartbeat" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="baseline">
            <RouteEvent eventName="LinuxAsmBaseline" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="software">
            <RouteEvent eventName="LinuxAsmSoftware" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="clamav">
            <RouteEvent eventName="LinuxAsmClamav" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="scan_event">
            <RouteEvent eventName="LinuxAsmScanEvent" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="alert">
            <RouteEvent eventName="LinuxAsmAlert" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="audit">
            <RouteEvent eventName="LinuxAsmAudit" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
          <MdsdEventSource source="kubelog">
            <RouteEvent eventName="kubelog" priority="Normal" storeType="CentralBond" />
          </MdsdEventSource>
        </MdsdEvents>
      </Events>
      <EventStreamingAnnotations>
        <EventStreamingAnnotation name="^.*$">
          <Cosmos>
            <Content><![CDATA[ <Config /> ]]></Content>
          </Cosmos>
        </EventStreamingAnnotation>
        <EventStreamingAnnotation name="syslog">
          <Cosmos>
            <Content><![CDATA[ <Config /> ]]></Content>
          </Cosmos>
        </EventStreamingAnnotation>
      </EventStreamingAnnotations>
    </MonitoringManagement>
  mdsautokey.cfg: |
    <config>
      <bootstrapkeys>
        <bootstrapkey>http://tuxtest.blob.core.windows.net/mamsasstore/TuxTest/MACommandXXXXXXXXXXXXXXXXXXXXX.xml?sv=2014-02-14XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</bootstrapkey>
      </bootstrapkeys>
    </config>
