apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: fluent-bit-logging
  template:
    metadata:
      labels:
        name: fluent-bit-logging
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.3.5
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
        readinessProbe:
          httpGet:
            path: /api/v1/metrics/prometheus
            port: 2020
        livenessProbe:
          httpGet:
            path: /
            port: 2020
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 500m
            memory: 600Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      - name: geneva
        env:
        - name: ROLE_INSTANCE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: juanlee/geneva
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 500m
            memory: 600Mi
        volumeMounts:
        - name: agent-certificates
          mountPath: /etc/mdsd.d/certs
        - name: agent-config
          mountPath: /etc/mdsd.d
        - name: config-cache
          mountPath: /etc/mdsd.d/config-cache
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: agent-certificates
        secret:
          secretName: agent-certificates
      - name: agent-config
        configMap:
          name: agent-config
      - name: config-cache
        emptyDir: {}
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
