# permissions for end users to view agentpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentpool-viewer-role
rules:
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - agentpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - agentpools/status
  verbs:
  - get
