name: build docker images

on:
    schedule:
        - cron: '0 */6 * * *'
    push:
        branches:
            - 'ace/dev'
            - master

jobs:
    bootstrap:
        name: build bootstrap image
        runs-on: ubuntu-latest
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        steps:
        - uses: actions/checkout@master
        - name: bootstrap
          run: -|
            jq --arg experimental enabled '. + {experimental: $experimental}' $HOME/.docker/config.json > $HOME/.docker/config.json
            docker buildx version
            