name: build docker images

on:
    schedule:
        - cron: '0 */6 * * *'
    push:
        branches:
            - master

jobs:
    bootstrap:
        name: build bootstrap image
        runs-on: ubuntu-latest
        env:
            
        steps:
        - uses: actions/checkout@master
        - name: bootstrap
          run: docker buildx version