name: bootstrap soak test mgmt cluster

on:
    # schedule daily for 3am PST == 11 UTC
    schedule:
        - cron: '0 */4 * * *'
    branches:
        - ace/dev
        
jobs:
    bootstrap:
        name: bootstrap mgmt cluster
        runs-on: ubuntu-latest
        env:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}  
        steps:
        - uses: actions/checkout@master
        - name: bootstrap
          run: -|
            go run ./cmd/bootstrap/bootstrap.go -f ./cmd/bootstrap/config.yaml --app ${AZURE_CLIENT_ID} --tenant ${AZURE_TENANT_ID} --key ${AZURE_CLIENT_SECRET}
            ls
            kubectl --kubeconfig ./kubeconfig get node
