name: bootstrap soak test mgmt cluster

on:
    schedule:
        - cron: '0 */4 * * *'
    push:
        branches:
            - 'ace/dev'
        
jobs:
    bootstrap:
        name: bootstrap mgmt cluster
        runs-on: ubuntu-latest
        env:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
        steps:
        - uses: actions/checkout@master
        - name: install kustomize
          run: |
            mkdir ${HOME}/kustomize
            cd ${HOME}/kustomize
            go mod init tmp
            go get sigs.k8s.io/kustomize/kustomize/v3@v3.5.4
            cd ${HOME}
            kustomize
            rm -rf ${HOME}kustomize
        - name: bootstrap
          run: |
            
            go run ./cmd/bootstrap/bootstrap.go -f ./cmd/bootstrap/config.yaml --app ${AZURE_CLIENT_ID} --tenant ${AZURE_TENANT_ID} --key ${AZURE_CLIENT_SECRET}
            kubectl --kubeconfig ./kubeconfig create secret generic flux-git-deploy --from-literal=identity="${SSH_KEY}" -o yaml | kubectl --kubeconfig ./kubeconfig apply -f -
            kustomize build ./cmd/bootstrap/manifests | kubectl --kubeconfig ./kubeconfig apply -f -
 